/** Generated by scripts/generate-image-dimensions.ts — do not edit. */
export const imageDimensions = {
  "/images/file-sharing-and-messages/clear-cache/desktop/button-clear-cache.png": {
    "width": 983,
    "height": 527
  },
  "/images/file-sharing-and-messages/clear-cache/desktop/confirm-removal-prompted-2.png": {
    "width": 655,
    "height": 296
  },
  "/images/file-sharing-and-messages/clear-cache/desktop/reupload-files-later-other-users-3.png": {
    "width": 991,
    "height": 835
  },
  "/images/file-sharing-and-messages/clear-cache/mobile/confirm-removal-prompted-5.jpg": {
    "height": 1328,
    "width": 648
  },
  "/images/file-sharing-and-messages/clear-cache/mobile/group-options-clear-cache-4.png": {
    "width": 648,
    "height": 1327
  },
  "/images/file-sharing-and-messages/clear-cache/mobile/reupload-files-later-other-users-6.jpg": {
    "height": 1328,
    "width": 648
  },
  "/images/file-sharing-and-messages/contact-book/add-contact-from-profile-3.jpg": {
    "height": 867,
    "width": 648
  },
  "/images/file-sharing-and-messages/contact-book/contact-book-private-list-saved-users-2.jpg": {
    "height": 867,
    "width": 648
  },
  "/images/file-sharing-and-messages/contact-book/contact-book-private-list-saved-users.png": {
    "width": 648,
    "height": 867
  },
  "/images/file-sharing-and-messages/contact-book/removing-contacts-profile-contacts-5.jpg": {
    "height": 1328,
    "width": 648
  },
  "/images/file-sharing-and-messages/contact-book/removing-contacts-profile-contacts-6.jpg": {
    "height": 1328,
    "width": 648
  },
  "/images/file-sharing-and-messages/contact-book/search-contacts-display-name-username-4.jpg": {
    "height": 867,
    "width": 648
  },
  "/images/file-sharing-and-messages/convert-incompatible-videos/desktop/banner-multiple-videos.png": {
    "width": 1224,
    "height": 810
  },
  "/images/file-sharing-and-messages/convert-incompatible-videos/desktop/banner-single-video.png": {
    "width": 1224,
    "height": 810
  },
  "/images/file-sharing-and-messages/convert-incompatible-videos/desktop/conversion-failed-retry.png": {
    "width": 1224,
    "height": 810
  },
  "/images/file-sharing-and-messages/convert-incompatible-videos/desktop/conversion-success.png": {
    "width": 1224,
    "height": 810
  },
  "/images/file-sharing-and-messages/convert-incompatible-videos/desktop/converting-progress.png": {
    "width": 1224,
    "height": 810
  },
  "/images/file-sharing-and-messages/convert-incompatible-videos/desktop/video-too-large.png": {
    "width": 1224,
    "height": 810
  },
  "/images/file-sharing-and-messages/convert-incompatible-videos/mobile/banner-multiple-videos.png": {
    "width": 393,
    "height": 852
  },
  "/images/file-sharing-and-messages/convert-incompatible-videos/mobile/banner-single-video.png": {
    "width": 393,
    "height": 852
  },
  "/images/file-sharing-and-messages/convert-incompatible-videos/mobile/conversion-failed-retry.png": {
    "width": 393,
    "height": 852
  },
  "/images/file-sharing-and-messages/convert-incompatible-videos/mobile/conversion-success.png": {
    "width": 393,
    "height": 852
  },
  "/images/file-sharing-and-messages/convert-incompatible-videos/mobile/converting-progress.png": {
    "width": 393,
    "height": 852
  },
  "/images/file-sharing-and-messages/convert-incompatible-videos/mobile/video-too-large.png": {
    "width": 393,
    "height": 852
  },
  "/images/file-sharing-and-messages/deleting-files-and-messages/desktop/clear-cache-6.png": {
    "width": 540,
    "height": 337
  },
  "/images/file-sharing-and-messages/deleting-files-and-messages/desktop/please-note-message-removal-permanent-2.png": {
    "width": 491,
    "height": 269
  },
  "/images/file-sharing-and-messages/deleting-files-and-messages/desktop/reupload-later-other-users-haven-8.png": {
    "width": 422,
    "height": 315
  },
  "/images/file-sharing-and-messages/deleting-files-and-messages/desktop/three-dots-next-message-delete.png": {
    "width": 536,
    "height": 274
  },
  "/images/file-sharing-and-messages/deleting-files-and-messages/desktop/will-prompted-confirm-file-removal-7.png": {
    "width": 514,
    "height": 310
  },
  "/images/file-sharing-and-messages/deleting-files-and-messages/mobile/long-press-message-clear-cache-9.jpg": {
    "height": 1459,
    "width": 1452
  },
  "/images/file-sharing-and-messages/deleting-files-and-messages/mobile/long-press-message-delete-3.jpg": {
    "height": 1459,
    "width": 713
  },
  "/images/file-sharing-and-messages/deleting-files-and-messages/mobile/please-note-message-removal-permanent-4.jpg": {
    "height": 417,
    "width": 713
  },
  "/images/file-sharing-and-messages/deleting-files-and-messages/mobile/removed-message-will-shown-chat-5.jpg": {
    "height": 601,
    "width": 702
  },
  "/images/file-sharing-and-messages/location-sharing/current-location-will-appear-chat-3.png": {
    "width": 788,
    "height": 621
  },
  "/images/file-sharing-and-messages/location-sharing/please-grant-access-device-location.jpg": {
    "height": 1008,
    "width": 540
  },
  "/images/file-sharing-and-messages/location-sharing/send-share-refresh-update-location-2.jpg": {
    "height": 1008,
    "width": 540
  },
  "/images/file-sharing-and-messages/messaging-on-keet/assign-member-roles-moderate-regular-16.png": {
    "width": 515,
    "height": 833
  },
  "/images/file-sharing-and-messages/messaging-on-keet/before-leaving-ll-asked-confirm-14.png": {
    "width": 655,
    "height": 273
  },
  "/images/file-sharing-and-messages/messaging-on-keet/change-mind-later-still-send-13.png": {
    "width": 512,
    "height": 275
  },
  "/images/file-sharing-and-messages/messaging-on-keet/depending-option-choose-contact-will-9.png": {
    "width": 594,
    "height": 323
  },
  "/images/file-sharing-and-messages/messaging-on-keet/find-username.png": {
    "width": 528,
    "height": 378
  },
  "/images/file-sharing-and-messages/messaging-on-keet/once-accept-request-conversation-will-12.png": {
    "width": 527,
    "height": 566
  },
  "/images/file-sharing-and-messages/messaging-on-keet/review-each-dm-request-choose-10.png": {
    "width": 594,
    "height": 274
  },
  "/images/file-sharing-and-messages/messaging-on-keet/review-each-dm-request-choose-11.png": {
    "width": 1135,
    "height": 768
  },
  "/images/file-sharing-and-messages/messaging-on-keet/share-profile-qr-code-5.png": {
    "width": 512,
    "height": 440
  },
  "/images/file-sharing-and-messages/messaging-on-keet/share-profile-qr-code-6.png": {
    "width": 524,
    "height": 766
  },
  "/images/file-sharing-and-messages/messaging-on-keet/share-profile-qr-code-7.jpg": {
    "height": 385,
    "width": 713
  },
  "/images/file-sharing-and-messages/messaging-on-keet/share-username-3.png": {
    "width": 510,
    "height": 395
  },
  "/images/file-sharing-and-messages/messaging-on-keet/share-username-4.png": {
    "width": 625,
    "height": 423
  },
  "/images/file-sharing-and-messages/messaging-on-keet/start-new-dm-both-participants-15.png": {
    "width": 572,
    "height": 275
  },
  "/images/file-sharing-and-messages/messaging-on-keet/user-profile-2.png": {
    "width": 527,
    "height": 672
  },
  "/images/file-sharing-and-messages/messaging-on-keet/write-invite-message-share-more-8.png": {
    "width": 590,
    "height": 532
  },
  "/images/file-sharing-and-messages/personal-group/add-details-new-chat-screenshot-3.png": {
    "width": 585,
    "height": 841
  },
  "/images/file-sharing-and-messages/personal-group/create-group-start-chat-button-top-screen.png": {
    "width": 530,
    "height": 284
  },
  "/images/file-sharing-and-messages/personal-group/explore-possibilities-screenshot-4.png": {
    "width": 1177,
    "height": 704
  },
  "/images/file-sharing-and-messages/personal-group/pop-up-new-group-screenshot-2.png": {
    "width": 644,
    "height": 534
  },
  "/images/file-sharing-and-messages/search-messages/find-specific-message-icon-enter.png": {
    "width": 596,
    "height": 252
  },
  "/images/file-sharing-and-messages/search-messages/once-match-found-jump-straight-2.png": {
    "width": 918,
    "height": 617
  },
  "/images/file-sharing-and-messages/sharing-files-and-media/chat-attach-file-button.png": {
    "width": 591,
    "height": 213
  },
  "/images/file-sharing-and-messages/sharing-files-and-media/desktop-download-process-status-bar-4.png": {
    "width": 462,
    "height": 193
  },
  "/images/file-sharing-and-messages/sharing-files-and-media/file-download-complete-status-will-5.png": {
    "width": 461,
    "height": 160
  },
  "/images/file-sharing-and-messages/sharing-files-and-media/files-want-share-peers-drag-2.png": {
    "width": 573,
    "height": 607
  },
  "/images/file-sharing-and-messages/sharing-files-and-media/hover-mouse-over-shared-file-6.png": {
    "width": 510,
    "height": 361
  },
  "/images/file-sharing-and-messages/sharing-files-and-media/shared-files-appear-chat-feed-3.png": {
    "width": 590,
    "height": 366
  },
  "/images/file-sharing-and-messages/snooze-notifications/desktop/choose-how-long-snooze-duration-3.png": {
    "width": 1224,
    "height": 810
  },
  "/images/file-sharing-and-messages/snooze-notifications/desktop/go-profile-select-notifications-sounds.png": {
    "width": 1224,
    "height": 810
  },
  "/images/file-sharing-and-messages/snooze-notifications/desktop/notifications-shows-active-snooze-remaining-4.png": {
    "width": 1224,
    "height": 810
  },
  "/images/file-sharing-and-messages/snooze-notifications/desktop/toggle-snooze-all-notifications-duration-2.png": {
    "width": 1224,
    "height": 810
  },
  "/images/file-sharing-and-messages/snooze-notifications/mobile/choose-how-long-snooze-duration-7.png": {
    "width": 393,
    "height": 852
  },
  "/images/file-sharing-and-messages/snooze-notifications/mobile/go-profile-tap-notifications-5.png": {
    "width": 393,
    "height": 929
  },
  "/images/file-sharing-and-messages/snooze-notifications/mobile/notifications-shows-active-snooze-remaining-8.png": {
    "width": 393,
    "height": 852
  },
  "/images/file-sharing-and-messages/snooze-notifications/mobile/tap-snooze-all-notifications-menu-6.png": {
    "width": 393,
    "height": 852
  },
  "/images/installation-and-setup/back-up-your-profile/backup-file-exported-desktop.png": {
    "width": 1224,
    "height": 810
  },
  "/images/installation-and-setup/back-up-your-profile/backup-file-exported-mobile.png": {
    "width": 393,
    "height": 852
  },
  "/images/installation-and-setup/back-up-your-profile/create-backup-file-desktop.png": {
    "width": 1224,
    "height": 810
  },
  "/images/installation-and-setup/back-up-your-profile/create-backup-file-mobile.png": {
    "width": 393,
    "height": 852
  },
  "/images/installation-and-setup/back-up-your-profile/export-backup-file-desktop.png": {
    "width": 1224,
    "height": 810
  },
  "/images/installation-and-setup/back-up-your-profile/export-backup-file-mobile.png": {
    "width": 393,
    "height": 852
  },
  "/images/installation-and-setup/back-up-your-profile/export-backup-file-save-dialog-desktop.png": {
    "width": 1224,
    "height": 810
  },
  "/images/installation-and-setup/back-up-your-profile/export-backup-file-save-dialog-mobile.png": {
    "width": 393,
    "height": 852
  },
  "/images/installation-and-setup/installation/android-google-play-listing.png": {
    "width": 524,
    "height": 185
  },
  "/images/installation-and-setup/installation/ios-app-store-listing.png": {
    "width": 480,
    "height": 138
  },
  "/images/installation-and-setup/installation/macos-dmg-download.png": {
    "width": 789,
    "height": 321
  },
  "/images/installation-and-setup/installation/windows-installer-download.png": {
    "width": 690,
    "height": 304
  },
  "/images/installation-and-setup/keet-username/change-username.png": {
    "width": 820,
    "height": 580
  },
  "/images/installation-and-setup/keet-username/set-username-popup.png": {
    "width": 716,
    "height": 649
  },
  "/images/installation-and-setup/keet-username/username-displayed-in-app.png": {
    "width": 523,
    "height": 338
  },
  "/images/installation-and-setup/keet-username/username-registration-rules.png": {
    "width": 656,
    "height": 491
  },
  "/images/installation-and-setup/keet-username/username-registry.png": {
    "width": 1200,
    "height": 630
  },
  "/images/installation-and-setup/link-devices/add-device-generate-pairing-link-2.jpg": {
    "height": 608,
    "width": 505
  },
  "/images/installation-and-setup/link-devices/confirm-setup-using-link-paste-link-copied-8.png": {
    "width": 417,
    "height": 693
  },
  "/images/installation-and-setup/link-devices/confirm-setup-using-link-paste-link-copied-9.jpg": {
    "height": 752,
    "width": 1600
  },
  "/images/installation-and-setup/link-devices/either-scan-qr-code-account-7.jpg": {
    "height": 670,
    "width": 1600
  },
  "/images/installation-and-setup/link-devices/keet-new-device-current-user-4.jpg": {
    "height": 2250,
    "width": 1600
  },
  "/images/installation-and-setup/link-devices/keet-profile-settings-my-devices.png": {
    "width": 521,
    "height": 510
  },
  "/images/installation-and-setup/link-devices/look-linked-device-want-delete-13.png": {
    "width": 613,
    "height": 405
  },
  "/images/installation-and-setup/link-devices/next-screen-choose-link-device-5.jpg": {
    "height": 581,
    "width": 1604
  },
  "/images/installation-and-setup/link-devices/qr-code-scan-later-3.png": {
    "width": 800,
    "height": 1006
  },
  "/images/installation-and-setup/link-devices/read-information-acceptable-tick-acknowledge-6.jpg": {
    "height": 1196,
    "width": 1600
  },
  "/images/installation-and-setup/link-devices/rename-current-device-profile-settings-10.png": {
    "width": 528,
    "height": 547
  },
  "/images/installation-and-setup/link-devices/rename-other-devices-repeat-process-11.png": {
    "width": 1080,
    "height": 1949
  },
  "/images/installation-and-setup/link-devices/unlink-device-which-no-longer-12.png": {
    "width": 648,
    "height": 618
  },
  "/images/installation-and-setup/setup/choose-display-name-manual-setup-4.png": {
    "width": 568,
    "height": 475
  },
  "/images/installation-and-setup/setup/choose-username-optional-but-manual-setup-5.png": {
    "width": 569,
    "height": 621
  },
  "/images/installation-and-setup/setup/choose-username-optional-but-manual-setup-6.png": {
    "width": 656,
    "height": 491
  },
  "/images/installation-and-setup/setup/complete-setting-up-manual-setup-7.png": {
    "width": 573,
    "height": 952
  },
  "/images/installation-and-setup/setup/download-keet-launch-new-keet-set-up.png": {
    "width": 568,
    "height": 531
  },
  "/images/installation-and-setup/setup/feel-free-add-profile-manual-setup-8.jpg": {
    "height": 1274,
    "width": 928
  },
  "/images/installation-and-setup/setup/manual-setup-3.png": {
    "width": 1276,
    "height": 1252
  },
  "/images/installation-and-setup/setup/quick-setup-2.png": {
    "width": 1151,
    "height": 610
  },
  "/images/keet-groups/admin-responsibilities/before-leaving-group-assign-another-3.png": {
    "width": 820,
    "height": 456
  },
  "/images/keet-groups/admin-responsibilities/group-members-renounce-admin-capabilities-2.png": {
    "width": 820,
    "height": 357
  },
  "/images/keet-groups/admin-responsibilities/keet-groups-fully-peer-peer.png": {
    "width": 1170,
    "height": 1651
  },
  "/images/keet-groups/create-a-group/create-read-only-group-chat-10.jpg": {
    "height": 720,
    "width": 804
  },
  "/images/keet-groups/create-a-group/desktop/enter-group-name-optionally-add-3.jpg": {
    "height": 808,
    "width": 581
  },
  "/images/keet-groups/create-a-group/desktop/new-group-chat-2.png": {
    "width": 644,
    "height": 534
  },
  "/images/keet-groups/create-a-group/desktop/screenshot-11.png": {
    "width": 581,
    "height": 808
  },
  "/images/keet-groups/create-a-group/desktop/start-chat-button.png": {
    "width": 530,
    "height": 284
  },
  "/images/keet-groups/create-a-group/enable-calls-8.png": {
    "width": 515,
    "height": 707
  },
  "/images/keet-groups/create-a-group/enable-calls-9.png": {
    "width": 525,
    "height": 708
  },
  "/images/keet-groups/create-a-group/mobile/enter-group-chat-name-description-6.jpg": {
    "height": 1179,
    "width": 576
  },
  "/images/keet-groups/create-a-group/mobile/group-will-appear-chat-list-7.png": {
    "width": 1170,
    "height": 1651
  },
  "/images/keet-groups/create-a-group/mobile/new-group-chat-5.jpg": {
    "height": 413,
    "width": 576
  },
  "/images/keet-groups/create-a-group/mobile/screenshot-12.jpg": {
    "height": 1179,
    "width": 576
  },
  "/images/keet-groups/create-a-group/mobile/start-chat-button-4.jpg": {
    "height": 840,
    "width": 1080
  },
  "/images/keet-groups/group-member-roles/admins-moderators-restrict-users-access.png": {
    "width": 576,
    "height": 590
  },
  "/images/keet-groups/group-member-roles/change-role-as-admin-moderator-2.png": {
    "width": 411,
    "height": 823
  },
  "/images/keet-groups/group-member-roles/upgrade-member-admin-administrators-downgrade-themselves-same-way-3.png": {
    "width": 576,
    "height": 863
  },
  "/images/keet-groups/group-moderation/as-group-moderator-administrator-have-2.png": {
    "width": 525,
    "height": 708
  },
  "/images/keet-groups/group-moderation/as-group-moderator-administrator-have.png": {
    "width": 515,
    "height": 833
  },
  "/images/keet-groups/group-moderation/list-reported-users-available-under-5.png": {
    "width": 526,
    "height": 843
  },
  "/images/keet-groups/group-moderation/list-reported-users-available-under-6.png": {
    "width": 513,
    "height": 843
  },
  "/images/keet-groups/group-moderation/mute-member-reversible-action-prevents-member-sending-7.png": {
    "width": 819,
    "height": 527
  },
  "/images/keet-groups/group-moderation/remove-member-admins-moderators-permanently-remove-peer-8.png": {
    "width": 702,
    "height": 1434
  },
  "/images/keet-groups/group-moderation/remove-member-admins-moderators-permanently-remove-peer-9.png": {
    "width": 702,
    "height": 1434
  },
  "/images/keet-groups/group-moderation/remove-member-user-will-no-longer-able-10.png": {
    "width": 525,
    "height": 314
  },
  "/images/keet-groups/group-moderation/review-reports-group-group-options-3.png": {
    "width": 659,
    "height": 888
  },
  "/images/keet-groups/group-moderation/review-reports-group-group-options-4.png": {
    "width": 659,
    "height": 886
  },
  "/images/keet-groups/invite-peers/choose-expiration-period-how-long-invite-will-remain-2.png": {
    "width": 458,
    "height": 820
  },
  "/images/keet-groups/invite-peers/generate-invite-group-add-member.png": {
    "width": 801,
    "height": 381
  },
  "/images/keet-groups/invite-peers/share-group-invite-link-they-join-pasting-link-search-3.png": {
    "width": 831,
    "height": 290
  },
  "/images/keet-groups/invite-peers/share-group-qr-code-ask-contact-scan-qr-code-4.jpg": {
    "height": 423,
    "width": 713
  },
  "/images/keet-groups/joining-groups/created-profile-discover-communities-enter-4.png": {
    "width": 1291,
    "height": 960
  },
  "/images/keet-groups/joining-groups/groups-may-interest-join-5.png": {
    "width": 634,
    "height": 944
  },
  "/images/keet-groups/joining-groups/keet-button-top-screen-button-3.jpg": {
    "height": 1419,
    "width": 1080
  },
  "/images/keet-groups/joining-groups/mobile-device-button-top-right-2.jpg": {
    "height": 385,
    "width": 713
  },
  "/images/keet-groups/joining-groups/receive-invite-link-peer-keet.png": {
    "width": 625,
    "height": 423
  },
  "/images/keet-groups/leave-group/all-related-files-will-removed-2.png": {
    "width": 655,
    "height": 259
  },
  "/images/keet-groups/leave-group/group-want-leave-leave-group.jpg": {
    "height": 299,
    "width": 433
  },
  "/images/keet-groups/leave-group/re-last-admin-ll-see-3.png": {
    "width": 655,
    "height": 288
  },
  "/images/security-and-privacy/group-options-user-member-list.png": {
    "width": 518,
    "height": 640
  },
  "/images/security-and-privacy/report-message-report-please-note-3.png": {
    "width": 372,
    "height": 256
  },
  "/images/security-and-privacy/report-user-group-options-user-5.png": {
    "width": 1170,
    "height": 2532
  },
  "/images/security-and-privacy/report-user-group-options-user-6.png": {
    "width": 1170,
    "height": 2532
  },
  "/images/security-and-privacy/report-user-group-options-user-7.png": {
    "width": 1170,
    "height": 2532
  },
  "/images/security-and-privacy/reported-message-content-will-hidden-4.png": {
    "width": 490,
    "height": 275
  },
  "/images/security-and-privacy/wont-receive-dm-requests-blocked-2.png": {
    "width": 903,
    "height": 669
  },
  "/images/technical-support-and-troubleshooting/delete-profile/once-ready-tick-understand-data-2.png": {
    "width": 560,
    "height": 498
  },
  "/images/technical-support-and-troubleshooting/delete-profile/screenshot.png": {
    "width": 528,
    "height": 710
  },
  "/images/technical-support-and-troubleshooting/keet-app-issues/repair-group-its-options-scroll-2.jpg": {
    "height": 1328,
    "width": 648
  },
  "/images/technical-support-and-troubleshooting/keet-app-issues/verify-online-checking-status-profile.jpg": {
    "height": 490,
    "width": 1080
  },
  "/images/technical-support-and-troubleshooting/notifications/desktop/profile-notifications-specify-how-receive.png": {
    "width": 407,
    "height": 829
  },
  "/images/technical-support-and-troubleshooting/notifications/ensure-keet-isn-restricted-device-7.png": {
    "width": 540,
    "height": 211
  },
  "/images/technical-support-and-troubleshooting/notifications/make-sure-device-isn-silent-6.jpg": {
    "height": 561,
    "width": 540
  },
  "/images/technical-support-and-troubleshooting/notifications/mobile/device-settings-apps-keet-notifications-3.jpg": {
    "height": 1107,
    "width": 540
  },
  "/images/technical-support-and-troubleshooting/notifications/mobile/device-settings-apps-keet-notifications-4.jpg": {
    "height": 1107,
    "width": 540
  },
  "/images/technical-support-and-troubleshooting/notifications/mobile/device-settings-apps-keet-notifications-5.png": {
    "width": 702,
    "height": 1450
  },
  "/images/technical-support-and-troubleshooting/notifications/mobile/here-toggle-app-sounds-sending-2.jpg": {
    "height": 517,
    "width": 648
  },
  "/images/technical-support-and-troubleshooting/notifications/not-yet-but-feature-may-8.webp": {
    "width": 426,
    "height": 240
  },
  "/images/technical-support-and-troubleshooting/recover-a-profile/add-file-and-input-password-desktop.png": {
    "width": 1224,
    "height": 810
  },
  "/images/technical-support-and-troubleshooting/recover-a-profile/add-file-and-input-password-mobile.png": {
    "width": 393,
    "height": 852
  },
  "/images/technical-support-and-troubleshooting/recover-a-profile/after-view-phrase-2.png": {
    "width": 637,
    "height": 882
  },
  "/images/technical-support-and-troubleshooting/recover-a-profile/im-a-current-user-desktop.png": {
    "width": 1224,
    "height": 810
  },
  "/images/technical-support-and-troubleshooting/recover-a-profile/im-a-current-user-mobile.png": {
    "width": 393,
    "height": 852
  },
  "/images/technical-support-and-troubleshooting/recover-a-profile/input-recovery-phrase-desktop.png": {
    "width": 1224,
    "height": 810
  },
  "/images/technical-support-and-troubleshooting/recover-a-profile/input-recovery-phrase-mobile.png": {
    "width": 393,
    "height": 852
  },
  "/images/technical-support-and-troubleshooting/recover-a-profile/profile-settings-privacy-security-recovery.png": {
    "width": 520,
    "height": 560
  },
  "/images/technical-support-and-troubleshooting/recover-a-profile/recover-profile-important-notice-desktop.png": {
    "width": 1224,
    "height": 810
  },
  "/images/technical-support-and-troubleshooting/recover-a-profile/recover-profile-important-notice-mobile.png": {
    "width": 393,
    "height": 852
  },
  "/images/technical-support-and-troubleshooting/recover-a-profile/recover-with-backup-file-desktop.png": {
    "width": 1224,
    "height": 810
  },
  "/images/technical-support-and-troubleshooting/recover-a-profile/recover-with-backup-file-mobile.png": {
    "width": 393,
    "height": 852
  },
  "/images/technical-support-and-troubleshooting/recover-a-profile/successful-recovery-desktop.png": {
    "width": 1224,
    "height": 810
  },
  "/images/technical-support-and-troubleshooting/recover-a-profile/successful-recovery-mobile.png": {
    "width": 393,
    "height": 852
  },
  "/images/technical-support-and-troubleshooting/recover-a-profile/typing-recovery-phrase-desktop.png": {
    "width": 1224,
    "height": 810
  },
  "/images/technical-support-and-troubleshooting/recover-a-profile/typing-recovery-phrase-mobile.png": {
    "width": 393,
    "height": 852
  },
  "/images/technical-support-and-troubleshooting/recover-a-profile/wrong-recovery-phrase-desktop.png": {
    "width": 1224,
    "height": 810
  },
  "/images/technical-support-and-troubleshooting/recover-a-profile/wrong-recovery-phrase-mobile.png": {
    "width": 393,
    "height": 852
  },
  "/images/technical-support-and-troubleshooting/sound-issues/check-correct-audio-device-selected-6.jpg": {
    "height": 427,
    "width": 713
  },
  "/images/technical-support-and-troubleshooting/sound-issues/mobile-settings-apps-keet-permissions-3.png": {
    "width": 966,
    "height": 528
  },
  "/images/technical-support-and-troubleshooting/sound-issues/please-note-after-update-reinstall-4.png": {
    "width": 652,
    "height": 302
  },
  "/images/technical-support-and-troubleshooting/sound-issues/unmute-microphone-call-options-panel-2.png": {
    "width": 856,
    "height": 393
  },
  "/images/technical-support-and-troubleshooting/sound-issues/unmute-microphone-call-options-panel.png": {
    "width": 428,
    "height": 796
  },
  "/images/technical-support-and-troubleshooting/sound-issues/verify-contact-has-microphone-enabled-5.png": {
    "width": 536,
    "height": 805
  },
  "/images/technical-support-and-troubleshooting/submit-a-report/copy-details-send-report-any-3.png": {
    "width": 663,
    "height": 893
  },
  "/images/technical-support-and-troubleshooting/submit-a-report/copy-details-send-report-any-4.png": {
    "width": 527,
    "height": 876
  },
  "/images/technical-support-and-troubleshooting/submit-a-report/encounter-error-send-report-immediately-2.png": {
    "width": 1048,
    "height": 318
  },
  "/images/technical-support-and-troubleshooting/submit-a-report/tell-us-ideas-improving-app.png": {
    "width": 658,
    "height": 888
  },
  "/images/technical-support-and-troubleshooting/video-issues/adjust-video-quality-settings-during-3.png": {
    "width": 1279,
    "height": 757
  },
  "/images/technical-support-and-troubleshooting/video-issues/mobile-settings-apps-keet-permissions-2.png": {
    "width": 966,
    "height": 528
  },
  "/images/technical-support-and-troubleshooting/video-issues/switch-cameras-calling-mobile-device-4.jpg": {
    "height": 925,
    "width": 950
  },
  "/images/technical-support-and-troubleshooting/video-issues/verify-have-granted-keet-necessary.png": {
    "width": 428,
    "height": 796
  },
  "/images/translate/desktop/messages-translated.png": {
    "width": 1224,
    "height": 810
  },
  "/images/translate/desktop/translate-from.png": {
    "width": 1225,
    "height": 1131
  },
  "/images/translate/desktop/translate-message-others.png": {
    "width": 1224,
    "height": 810
  },
  "/images/translate/desktop/translate-modal.png": {
    "width": 1224,
    "height": 810
  },
  "/images/translate/desktop/translate-to.png": {
    "width": 1225,
    "height": 1219
  },
  "/images/translate/desktop/translation-downloading.png": {
    "width": 1224,
    "height": 810
  },
  "/images/translate/desktop/translation-options.png": {
    "width": 1224,
    "height": 810
  },
  "/images/translate/mobile/messages-translated.png": {
    "width": 393,
    "height": 852
  },
  "/images/translate/mobile/translate-from.png": {
    "width": 393,
    "height": 852
  },
  "/images/translate/mobile/translate-message-others.png": {
    "width": 393,
    "height": 852
  },
  "/images/translate/mobile/translate-modal.png": {
    "width": 393,
    "height": 852
  },
  "/images/translate/mobile/translate-to.png": {
    "width": 393,
    "height": 852
  },
  "/images/translate/mobile/translation-downloading.png": {
    "width": 393,
    "height": 852
  },
  "/images/translate/mobile/translation-options.png": {
    "width": 393,
    "height": 852
  },
  "/images/voice-and-video-calls/video-calls-and-share-screen/screenshot.png": {
    "width": 1294,
    "height": 767
  },
  "/images/voice-and-video-calls/voice-calls/alternatively-start-call-group-either-2.png": {
    "width": 928,
    "height": 363
  },
  "/images/voice-and-video-calls/voice-calls/call-controls-manage-screen-sharing-4.jpg": {
    "height": 618,
    "width": 1080
  },
  "/images/voice-and-video-calls/voice-calls/join-ongoing-call-was-started-3.png": {
    "width": 925,
    "height": 272
  },
  "/images/voice-and-video-calls/voice-calls/start-direct-call-need-have.jpg": {
    "height": 805,
    "width": 713
  }
} as const;

export type ImageDimensionPath = keyof typeof imageDimensions;

export function lookupImageDimensions(
  src: string,
): { width: number; height: number } | undefined {
  const normalized = src.split('?')[0];
  return imageDimensions[normalized as ImageDimensionPath];
}
