/**
 * Scan public/images and emit src/lib/image-dimensions.generated.ts so DocsImage
 * can set display widths during SSR/static export (not only after onLoad).
 */
import { readFileSync, readdirSync, statSync, writeFileSync } from 'fs';
import { extname, join, relative } from 'path';

const IMAGES_DIR = join(process.cwd(), 'public/images');
const OUT_FILE = join(process.cwd(), 'src/lib/image-dimensions.generated.ts');

function readPngSize(buf: Buffer): { width: number; height: number } | null {
  if (buf.length < 24 || buf.toString('ascii', 1, 4) !== 'PNG') return null;
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

function readJpegSize(buf: Buffer): { width: number; height: number } | null {
  if (buf.length < 4 || buf[0] !== 0xff || buf[1] !== 0xd8) return null;

  let i = 2;
  while (i + 9 < buf.length) {
    if (buf[i] !== 0xff) {
      i += 1;
      continue;
    }

    const marker = buf[i + 1];
    const len = buf.readUInt16BE(i + 2);
    if (len < 2) break;

    if (marker === 0xc0 || marker === 0xc1 || marker === 0xc2) {
      return {
        height: buf.readUInt16BE(i + 5),
        width: buf.readUInt16BE(i + 7),
      };
    }

    i += 2 + len;
  }

  return null;
}

function readWebpSize(buf: Buffer): { width: number; height: number } | null {
  if (buf.length < 30 || buf.toString('ascii', 0, 4) !== 'RIFF') return null;
  if (buf.toString('ascii', 8, 12) !== 'WEBP') return null;

  const chunk = buf.toString('ascii', 12, 16);

  if (chunk === 'VP8 ') {
    return {
      width: buf.readUInt16LE(26) & 0x3fff,
      height: buf.readUInt16LE(28) & 0x3fff,
    };
  }

  if (chunk === 'VP8L' && buf.length >= 25) {
    const bits = buf.readUInt32LE(21);
    return {
      width: (bits & 0x3fff) + 1,
      height: ((bits >> 14) & 0x3fff) + 1,
    };
  }

  if (chunk === 'VP8X' && buf.length >= 30) {
    const w = 1 + (buf[24] | (buf[25] << 8) | (buf[26] << 16));
    const h = 1 + (buf[27] | (buf[28] << 8) | (buf[29] << 16));
    return { width: w, height: h };
  }

  return null;
}

function readImageSize(file: string): { width: number; height: number } | null {
  const buf = readFileSync(file);
  const ext = extname(file).toLowerCase();

  if (ext === '.png') return readPngSize(buf);
  if (ext === '.jpg' || ext === '.jpeg') return readJpegSize(buf);
  if (ext === '.webp') return readWebpSize(buf);

  return readPngSize(buf) ?? readJpegSize(buf) ?? readWebpSize(buf);
}

function walkImages(dir: string): string[] {
  const files: string[] = [];

  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      files.push(...walkImages(full));
      continue;
    }

    if (/\.(png|jpe?g|webp)$/i.test(entry)) {
      files.push(full);
    }
  }

  return files;
}

function main(): void {
  const files = walkImages(IMAGES_DIR);
  const dimensions: Record<string, { width: number; height: number }> = {};

  for (const file of files) {
    const size = readImageSize(file);
    if (!size) {
      console.warn(`⚠️  Could not read dimensions: ${file}`);
      continue;
    }

    const publicPath = `/${relative(join(process.cwd(), 'public'), file).replace(/\\/g, '/')}`;
    dimensions[publicPath] = size;
  }

  const body = `/** Generated by scripts/generate-image-dimensions.ts — do not edit. */
export const imageDimensions = ${JSON.stringify(dimensions, null, 2)} as const;

export type ImageDimensionPath = keyof typeof imageDimensions;

export function lookupImageDimensions(
  src: string,
): { width: number; height: number } | undefined {
  const normalized = src.split('?')[0];
  return imageDimensions[normalized as ImageDimensionPath];
}
`;

  writeFileSync(OUT_FILE, body);
  console.log(`✅ Wrote ${Object.keys(dimensions).length} image dimensions to ${relative(process.cwd(), OUT_FILE)}`);
}

main();
